I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day1.rpy", line 86, in script
    if geoF and webF and iotF and cloudF:
  File "game/day1.rpy", line 86, in <module>
    if geoF and webF and iotF and cloudF:
NameError: name 'geoF' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day1.rpy", line 86, in script
    if geoF and webF and iotF and cloudF:
  File "C:\Users\franc\Documents\renpy-8.3.2-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\franc\Documents\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\franc\Documents\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/day1.rpy", line 86, in <module>
    if geoF and webF and iotF and cloudF:
NameError: name 'geoF' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
FindYourTrack 1.0
Fri Oct 11 11:14:15 2024
